extends: airbnb
plugins:
  - react
  - jsx-a11y
  - import

rules:
  react/prefer-stateless-function: 0
  comma-dangle: 0
  max-len: 0
  no-multiple-empty-lines: 0
  no-unused-vars: 1
  quotes: 0
  semi: 1
