# Sass lint config
rules:
  class-name-format: 0
  leading-zero: 0
  no-color-literals: 0
  no-css-comments: 0
  no-misspelled-properties: 0
  placeholder-name-format: 0
  property-sort-order: 0
  variable-name-format: 0
